apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMaps.name }}
  namespace: {{ .Release.Namespace }}
data: 
  EMAIL_HOST: {{ .Values.configMaps.crawljpyappconfig.emailHost | quote }}
  EMAIL_USE_TLS: {{ .Values.configMaps.crawljpyappconfig.emailUseTls | quote }}
  REDIS_HOST: {{ .Values.configMaps.crawljpyappconfig.redisHost | quote }}
  REDIS_PORT: {{ .Values.configMaps.crawljpyappconfig.redisPort | quote }}
  POSTGRES_DB: {{ .Values.configMaps.crawljpyappconfig.postgresDB | quote }}
  POSTGRES_HOST: {{ .Values.configMaps.crawljpyappconfig.postgresHost | quote }}
  POSTGRES_PORT: {{ .Values.configMaps.crawljpyappconfig.postgresPort | quote }}
  STATE: {{ .Values.configMaps.crawljpyappconfig.state | quote }}
  SAMPLE_EMAIL_ADDRESS: {{ .Values.configMaps.crawljpyappconfig.sampleemailaddress | quote }}