apiVersion: batch/v1
kind: Job
metadata:
  name: deployment-job
  namespace: {{ .Release.Namespace }}
  labels:
    app: database-migrate
    env: production
spec:
  template:
    spec:
      containers:
        - name: deployment-job-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          envFrom:
          - configMapRef:
              name: {{ .Values.configMaps.name }}
          - secretRef:
              name: {{ .Values.secrets.name }}

          
          command: ["/bin/sh"]
          args: ["-c", "sleep 10 && python deployment.py"]
      restartPolicy: Never
  
