apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  EMAIL_HOST_USER: {{ .Values.secrets.crawljoyappsecret.emailHostUser | b64enc | quote }}
  EMAIL_HOST_PASSWORD: {{ .Values.secrets.crawljoyappsecret.emailHostPassword | b64enc | quote }}
  POSTGRES_USER: {{ .Values.secrets.crawljoyappsecret.postgresUser | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.crawljoyappsecret.postgressPassword | b64enc | quote }}
