apiVersion: batch/v1
kind: CronJob
metadata:
  name: syncdb-cronjob
  namespace: {{ .Release.Namespace }}

spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: syncdb-container
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              envFrom:
              - configMapRef:
                  name: {{ .Values.configMaps.name }}
              - secretRef:
                  name: {{ .Values.secrets.name }}

              command: ["/bin/sh"]
              args: ["-c", "python syncdb.py"]
          restartPolicy: OnFailure