apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.secrets.crawljoypostgressecret.postgresUser | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.crawljoypostgressecret.postgresPassword | b64enc | quote }}