apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: db
    env: production 
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
