apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: {{ .Release.Namespace }}
  labels:
    app: redis
    env: production   
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: redis
      env: production   
  template:
    metadata:
      name: redis
      labels:
        app: redis
        env: production   
    spec:
      containers:
        - name: redis-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 6379
          resources:
            {{ toYaml .Values.resources | nindent 12 }}
