apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: redis
    env: production   
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
