apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMaps.name }}
  namespace: {{ .Release.Namespace }}
data: 
  EMAIL_HOST: {{ .Values.configMaps.config.emailHost | quote }}
  EMAIL_USE_TLS: {{ .Values.configMaps.config.emailUseTls | quote }}
  CRAWLER_POSTGRES_DB: {{ .Values.configMaps.config.postgresDB | quote }}