apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    name: {{ .Values.name }}-deployment
    project: {{ .Values.labels.project }}
    env: {{ .Values.labels.env }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ .Values.name }}-api
      project: {{ .Values.labels.project }}
      env: {{ .Values.labels.env }}
  template:
    metadata:
      labels:
        name: {{ .Values.name }}-api
        project: {{ .Values.labels.project }}
        env: {{ .Values.labels.env }}
    spec:      
      containers:
        - name: {{ .Values.name }}-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          envFrom:
            - configMapRef:
                name: {{ .Values.configMaps.name }}
            - secretRef:
                name: {{ .Values.secrets.name }}
          resources:
            {{ toYaml .Values.resources | nindent 12 }}

