apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  EMAIL_HOST_USER: {{ .Values.secrets.secret.emailHostUser | b64enc | quote }}
  EMAIL_HOST_PASSWORD: {{ .Values.secrets.secret.emailHostPassword | b64enc | quote }}
  CRAWLER_POSTGRES_USER: {{ .Values.secrets.secret.postgresUser | b64enc | quote }}
  CRAWLER_POSTGRES_PASSWORD: {{ .Values.secrets.secret.postgressPassword | b64enc | quote }}
  DJANGO_SECRET_KEY: {{ .Values.secrets.secret.secretKey | b64enc | quote  }}