# Generated by Django 4.1.2 on 2024-03-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarAd',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=4)),
                ('mileage', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=50)),
                ('body_status', models.CharField(max_length=50)),
                ('modified_date', models.DateTimeField()),
            ],
        ),
    ]
